services:
  cloak:
    image: ghcr.io/dpidetector/node-cloak
    build:
      context: .
      dockerfile: ./protos/cloak/Dockerfile
    env_file:
      - "user.conf"
    # logging:
    #   driver: local
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    restart: always
    # restart: on-failure:3
    logging:
      options:
        max-size: 30M

  shadowsocks:
    image: ghcr.io/dpidetector/node-shadowsocks
    build:
      context: .
      dockerfile: ./protos/shadowsocks/Dockerfile
    env_file:
      - "user.conf"
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    restart: always
    logging:
      options:
        max-size: 30M

  amnezia-wireguard:
    image: ghcr.io/dpidetector/node-amnezia-wireguard
    build:
      context: .
      dockerfile: ./protos/amnezia-wireguard/Dockerfile
    env_file:
      - "user.conf"
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    restart: always
    logging:
      options:
        max-size: 30M

  wireguard:
    image: ghcr.io/dpidetector/node-wireguard
    build:
      context: .
      dockerfile: ./protos/wireguard/Dockerfile
    env_file:
      - "user.conf"
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    restart: always
    logging:
      options:
        max-size: 30M

  openvpn-tlscrypt:
    image: ghcr.io/dpidetector/node-openvpn-tlscrypt
    build:
      context: .
      dockerfile: ./protos/openvpn-tlscrypt/Dockerfile
    env_file:
      - "user.conf"
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    restart: always
    logging:
      options:
        max-size: 30M

  openvpn:
    image: ghcr.io/dpidetector/node-openvpn
    build:
      context: .
      dockerfile: ./protos/openvpn/Dockerfile
    env_file:
      - "user.conf"
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    restart: always
    logging:
      options:
        max-size: 30M

  anyconnect:
    image: ghcr.io/dpidetector/node-anyconnect
    build:
      context: .
      dockerfile: ./protos/anyconnect/Dockerfile
    env_file:
      - "user.conf"
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    restart: always
    logging:
      options:
        max-size: 30M

  custom:
    image: ghcr.io/dpidetector/node-custom
    build:
      context: .
      dockerfile: ./protos/custom/Dockerfile
    env_file:
      - "user.conf"
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    restart: always
    logging:
      options:
        max-size: 30M
